version: '3'
services:
  postgres:
    container_name: auction_postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: auction_user
      POSTGRES_PASSWORD: auction_password
      POSTGRES_DB: auction_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auction_user"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - auction_network

  pgadmin:
    container_name: auction_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - auction_network

volumes:
  postgres_data:

networks:
  auction_network:
    driver: bridge
